# Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [20]:
def np_array_N_down(N):
    import numpy as np
    return np.arange(N-1,-1,-1)

print(np_array_N_down(10))

[9 8 7 6 5 4 3 2 1 0]


# Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [26]:
def np_diag_N_down(N):
    import numpy as np
    return np.sum(np.diag(np.arange(N-1,-1,-1), k=0))

print(np_diag_N_down(10))

45


# Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [15]:
def solver(input_option=True, koefs_left=[],koefs_right=[]):
    """
    Функция преддназначена для решения систем линейных уравнений
    Предусматривает ручной ввод коэфициентов или расчет на основе уже существующих переменных
    """
    import numpy as np
    from numpy import linalg
    if input_option:
        print('Введите количество уравнений в системе:')
        N=int(input())

        koefs_left = np.zeros((N,N))
        koefs_right = np.zeros((N,1))

        for eq in range(N):
            print(f"Для уравнения номер {eq+1} из {N} введите последовательно коэфициенты")
            for koef in range(N+1):
                x = int(input())
                if koef<N:
                    koefs_left[eq][koef]=x
                else: 
                    koefs_right[eq][0]=x
    print(koefs_left)
    print(koefs_right)
    if np.allclose( np.dot(koefs_left, linalg.solve(koefs_left, koefs_right)), koefs_right):
        return linalg.solve(koefs_left, koefs_right)

    
import numpy as np
from numpy import linalg    
koefs_left = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
koefs_right = np.array([4, 12, -3])

solver(False, koefs_left, koefs_right)
# solver()

[[4 2 1]
 [1 3 0]
 [0 5 4]]
[ 4 12 -3]


array([ 0.46666667,  3.84444444, -5.55555556])